const UserActionTypes = {
    SIGN_IN_START: 'SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    SIGN_UP_START:'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_START',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    SIGN_OUT: 'SIGN_OUT',
    FETCH_INVOICE_START: 'FETCH_INVOICE_START',
    FETCH_INVOICE_SUCCESS: 'FETCH_INVOICE_SUCCESS',
    FETCH_INVOICE_FAILURE: 'FETCH_INVOICE_FAILURE'
}

export default UserActionTypes